alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
- rule: DEPLOYMENT_LIVE
domains:
- domain: snakem.xericode.dev
  type: PRIMARY
  zone: xericode.dev
ingress:
  rules:
  - component:
      name: snakem-server
    match:
      path:
        prefix: /
name: snakem-app-dev
region: nyc
services:
- dockerfile_path: Dockerfile
  github:
    branch: master
    deploy_on_push: true
    repo: krazkidd/snakem
  health_check:
    http_path: /api/health
  http_port: 9000
  instance_count: 1
  instance_size_slug: basic-xxs
  name: snakem-server
  source_dir: /
