alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
- rule: DEPLOYMENT_LIVE
domains:
- domain: snakem.app.xericode.net
  type: PRIMARY
  zone: app.xericode.net
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: web
    match:
      path:
        prefix: /
  - component:
      name: server
      preserve_path_prefix: true
    match:
      path:
        prefix: /api
  - component:
      name: server
      preserve_path_prefix: true
    match:
      path:
        prefix: /ws
name: snakem-app
region: nyc
services:
- dockerfile_path: Dockerfile
  github:
    branch: master
    deploy_on_push: true
    repo: krazkidd/snakem
  health_check:
    http_path: /api/health
  http_port: 9000
  instance_count: 1
  instance_size_slug: basic-xxs
  name: server
  source_dir: /
static_sites:
- build_command: npm run build
  environment_slug: python
  github:
    branch: split-web
    deploy_on_push: true
    repo: krazkidd/snakem
  name: web
  output_dir: dist
  source_dir: /web
