alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
ingress:
  rules:
    - component:
        name: snakem
      match:
        path:
          prefix: /
name: snakem-dev
region: nyc
services:
  - dockerfile_path: Dockerfile
    github:
      branch: master
      deploy_on_push: true
      repo: krazkidd/snakem
    health_check:
      period_seconds: 90
      timeout_seconds: 30
      port: 11844
      initial_delay_seconds: 10
    http_port: 11845
    internal_ports: [11844, 11845]
    instance_count: 1
    instance_size_slug: basic-xxs
    name: snakem-server
    source_dir: /
