/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    GameDisplay: typeof import('./src/components/GameDisplay.vue')['default']
    HighScores: typeof import('./src/components/HighScores.vue')['default']
    MessageOfTheDay: typeof import('./src/components/MessageOfTheDay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
